### ISSUE TITLE
Pre-flight checklist

### ISSUE THREAD

**Issue by jfnl88** [fizzstudio/EXPERt#18]
EXPERt
- Have all tasks (even built-ins) been tested using the very latest code base?
- Has testing been performed with multiple simultaneous users?
- Has the server been updated with the latest version?
Bundle
- Is all expected response data present in the output files?
- Are any timeouts set appropriately?
- Does the 'Return to Prolific' button show up?
- Has the Prolific URL been updated?
- Have all necessary 'build' commands been run?
- Is the bundle source configured to run all desired tasks?
- Has the latest source been uploaded?
- Have the profiles been rebuilt if necessary?

**Comment by jfnl88** [comment]
# Chartmob 3
## EXPERt

- [ ] Have all tasks in the experiment (even EXPERt built-ins) been tested with the EXPERt version to be used?
- [ ] Has testing been performed with multiple simultaneous users?
- [ ] Has the server been updated with the EXPERt version to be used?

## Bundle

- [ ] Is all expected response data present in the output files?
- [ ] Are any timeouts set appropriately?
- [ ] Does the 'Return to Prolific' button show up?
- [ ] Has the 'Return to Prolific' URL been updated?
- [ ] Have all necessary 'build' commands been run?
- [ ] Is the bundle source configured to run all desired tasks?
- [ ] Are the params for number of conditions and participants set correctly?
- [ ] Has the latest source been uploaded?
- [ ] Have the profiles on the server been rebuilt if necessary?
- [ ] Has a new run been started?
